#!/usr/bin/env bash
# Define colors
source map.txt
# here defined FILE_MAP
yellow='\e[93m'
green='\e[32m'
black='\e[40m'

# select names of all changed files
ALL_FILES=`git diff-index --name-only  HEAD`
echo 'all files' ${ALL_FILES}
for FILE in $(echo $ALL_FILES | tr '\n' ' '); do
  if [ ! ${FILE_MAP[$FILE]} ]; then
    echo -e "${yellow}file $FILE need to be in FILE_MAP"
    exit 0
  fi;
  echo -e "${green}$FILE ${FILE_MAP[$FILE]}${black}";
  cp "$FILE" ${FILE_MAP[$FILE]}
done
